"""
Django settings for exam_approval_backend project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
## might be problems with installed apps i n settings
## or host names in mongodb connect
## or any change in models, serialisers. We have not yetr changed views.py
## need to modify or provide atrleast the data of the database "engine" .. as it was mentioned 

from pathlib import Path
import os
import mongoengine
from mongoengine import connect
import datetime
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tx(e01n5-9#sz#j6qa=_+^%se0k1md-@t)&b%g%^!crh_1bh*g'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
# ALLOWED_HOSTS = ['localhost', '127.0.0.1']

DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'djongo',
    'exam_app',
    'rest_framework',
    'rest_framework_mongoengine',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'exam_approval_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'exam_approval_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'your_database_name',
#         'HOST': 'localhost',
#         'PORT': 27017,
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'db30',
#         'HOST': 'localhost',
#         'PORT': 27017,
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': '',  
        
#     }
# }
# mongodb://127.0.0.1:27017
#mongoengine.disconnect()

# MONGO_USER_NAME = "sirshendu"
# MONGO_PASSWORD = "271828"
# MONGO_ADDRESS = "127.0.0.1:27017"
# mongoengine.connect(db='db30', host=f'mongodb://{MONGO_USER_NAME}:{MONGO_PASSWORD}@{MONGO_ADDRESS}/')

MONGO_USER_NAME = "sirshendu2e01"
MONGO_PASSWORD = "HKIsXoMif7yM4KAl"
MONGO_ADDRESS = "cluster0.flmhac1.mongodb.net"
mongoengine.connect(db='db40', host=f'mongodb+srv://{MONGO_USER_NAME}:{MONGO_PASSWORD}@{MONGO_ADDRESS}/')

# mongodb+srv://sirshendu2e01:<password>@cluster0.flmhac1.mongodb.net/?retryWrites=true&w=majority







#mongoengine.connect(db='db30', host='mongodb://127.0.0.1:27017/')
DATABASES = {
    # 'default': {
    #  'ENGINE': 'django.db.backends.sqlite3',
    #  'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db31',
        'USER': 'sir2',
        'PASSWORD': '271828',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}
#mongoengine.connect(db='db30', host='127.0.0.1', port=27017)



JWT_SECRET_KEY = 'mysecretkey1234!@#$'
JWT_EXPIRATION_DELTA = datetime.timedelta(days=7)
JWT_ALGORITHM = 'HS256'
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
